# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7oIv8M0UmHv1cFpo85TZHmqo3EERkj4
"""

if True:
  print('Kode program ini akan dieksekusi')

if False:
  print('Kode program ini tidak akan dieksekusi')
print('Kode program ini akan selalu dieksekusi karena tidak termasuk percobaan')

nilai = 70.5
print('Nilai anda adalah:', nilai, '\n')
if nilai >= 70:
  print('Selamat, anda lulus!')
else:
  print('Maaf, anda tidak lulus.')

nilai = int(input('Masukan nilai anda:'))
print('Nilai anda adalah:', nilai, '\n')
if nilai >= 70:
  print('Selamat, anda lulus!')
else:
  print('Maaf, anda tidak lulus.')

nilai = int(input('Masukan nilai anda:'))

if nilai >= 90:
  print('Predikat A')
if nilai >= 90:
  print('Predikat A')
elif nilai >= 80:
  print('Predikat B')
elif nilai >= 60:
  print('Predikat C')
elif nilai >= 40:
  print('Predikat D')
else:
  print('Predikat E')

buah_yang_tersedia = ['Jeruk', 'Mangga', 'Nanas', 'Apel']
buah_yang_dicari = input('Masukan nama buah dalam huruf kapital: ')
if (buah_yang_dicari in buah_yang_tersedia):
  print('Buah yang anda cari tersedia!')
else:
  print('Buah yang anda cari tidak tersedia!')