# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNM6H2k6ABMY_pjtBXaE8lxBiCiYxxhz
"""

for nilai in sequence:
  # blok kode for

listkota = [
'jakarta', 'surabaya', 'depok', 'bekasi','solo', 'jogjakarta', 'semarang', 'makassar'
]
for kota in listkota :
             print(kota)

## 0 sampai 4
for i in range(5):
  print("perulangan ke -",i)

## 10 sampai 15
for i in range(10,16):
  print('i=', i)

## bilangan genap kelipatan 2
for i in range(2,12,2):
  print('i=', i)

## bilangan ganjil kelipatan 2
for bilangan_ganjil in range(1,12,2):
  print(bilangan_ganjil)

tuplebuah = ('mangga','jeruk','apel','pepaya')
for buah in tuplebuah:
  print(buah)

for karakter in"indonesiaid":
  print(karakter)

for i in range(10,20):
  # skip jika i == 15
   if (i == 15):
    continue
   print(i)

for i in range(10,20):
  # hentikan jika i == 15
  if (i == 15):
    break
  print(i)

listkota = [
    'jakarta','surabaya','depok', 'bekasi','solo'
    'jogjakarta','semarang','makassar'
]
for kota in listkota:
  print(kota)
else:
  print('tidak ada lagi item yang tersisa')

listkota = [
    'jakarta','surabaya','depok','bekasi','solo','jogjakarta','semarang','makassar'
]

kotaYangDicari = input('ketik nama kota yang kamu cari:')

for i, kota in enumerate(listkota):
  # kita ubah katanya ke lowercase jadi
  # menjadi case insensitive
  if kota.lower() == kotaYangDicari.lower():
    print('kota yang anda cari berada pada indeks',i)
    break
else:
  print('maaf, kota yang anda cari tidak ada')